
#ifndef puttCalc_incl
# define puttCalc_incl
//
// This file is automatically generated by createcc. Do not edit!
//	(OG)

#include <cstdio>
typedef	char * _CP;

class _puttCalc_parameter {
	public:
		int	inc;	//increment
		int 	inc_flag;
		char *	campatt;	//camera file pattern
		int 	campatt_flag;
		char *	fn2;	//file name2
		int 	fn2_flag;
		int	deint;	//Deinterlace video: 0=no, 1=field 1 up, 2=field 1+2
		int 	deint_flag;
		int	dx;	//image width for raw file formats
		int 	dx_flag;
		char *	cfn;	//config file
		int 	cfn_flag;
		int	dy;	//image height for raw file formats
		int 	dy_flag;
		int	filt;	//filter for YUV conversion: 0=no, 1=2-tab, 2=4-tab, 3=6-tab
		int 	filt_flag;
		int	fmt;	//file format (1= raw (RGB), 2= raw (BGR), 3= YCbCr)
		int 	fmt_flag;
		char *	fn;	//file name
		int 	fn_flag;
		char *	cam;	//camera file
		int 	cam_flag;
		char *	patt2;	//file pattern2
		int 	patt2_flag;
		int	end;	//end
		int 	end_flag;
		char *	outpatt;	//output file pattern
		int 	outpatt_flag;
		int	start;	//start
		int 	start_flag;
		char *	patt;	//file pattern
		int 	patt_flag;
		int	help_flg;
		_puttCalc_parameter ();
		~_puttCalc_parameter ();
		int ReadInt(int &i, char *s, int min, int max);
		int ReadUShort(unsigned short &i, char *s);
		int ReadShort(short &i, char *s);
		int ReadShort(short &i, char *s, short min, short max);
		int ReadDouble(double &i, char *s);
		int ReadDouble(double &i, char *s, double min, double max);
		int ParseArg( int   argc, char **argv );
		int ParseStr( const char *s );
		int ReadConfig( FILE *fp);
		void PrintHelp(  FILE *fp, const char *pn ="puttCalc" );
		void Print(FILE *fp);
		bool IsStrict() const {return is_strict;}
		void SetStrict(bool v) {is_strict=v;}
	private:
		bool is_strict;
};


// @return 1 if success, 0 if -h was specified and < 0 in case of parse errors
int ParseArg_puttCalc (int argc, char *argv[],_puttCalc_parameter  & para );

//
#endif
